### PR TITLE
make gorun pip installable

### PR DESCRIPTION
**Pull request by magopian**
This is to fix issue #1.

What changed:
- new requirements.txt file to list pyinotify
- "translated" README.md to README.rst (compatible with long_description)
- modified "installation" in the README.rst (to use pip)
- improved and complete setup.py (use requirements.txt and README.rst)
- MANIFEST.in to add README.rst and requirements.txt to the package
- new LICENSE file

Please note that I've used the BSD license, as it's the one I'm used too, but obviously, feel free to change it by:
- changing the content of the LICENSE file
- changing the "license" parameter in the setup.py

To make it available on PyPI:

```
python setup.py sdist
python setup.py register # you need to have created an account on http://pypi.python.org first
python setup.py upload
```

### CODE REVIEW

**Comment by magopian** [comment]
would you (or anybody else reading this actually) mind if i handle the uploading and registering on PyPI for you?

You (@peterbe) would obviously be the author, i'd only be the maintainer, for the time being, until you find time/motivation to do it yourself. At which point i'll more than happily delete my package on PyPI to allow you to upload yours!

Just want to make it clear that this is not an attempt at "stealing", but more to make it (gorun) as easily installable as possible (<3 pip requirements ;).

Thoughts?

**Comment by peterbe** [comment]
Arhh!! How could I have missed this awesome pull request. I'm soo sorry. I'll merge it and make sure it's on pypi.

**Comment by peterbe** [comment]
All thanks to you!
http://pypi.python.org/pypi/gorun/1.7

**Comment by magopian** [comment]
Thanks a ton peterbe, first of all for this awesome piece of software I'm using daily, and for making my life even easier by putting it on PyPI ;)

**Pull request merged**
